const athleteData = {
  'Michael Ii': [
    { year: 2000, gold: 0, silver: 0, bronze: 0 },
    { year: 2004, gold: 6, silver: 0, bronze: 2 },
    { year: 2008, gold: 8, silver: 0, bronze: 0 },
    { year: 2012, gold: 4, silver: 2, bronze: 0 },
    { year: 2016, gold: 5, silver: 3, bronze: 2 },
  ],
  'Larysa (diriy-)': [
    { year: 1956, gold: 4, silver: 1, bronze: 1 },
    { year: 1960, gold: 3, silver: 2, bronze: 1 },
    { year: 1964, gold: 2, silver: 2, bronze: 2 },
  ],
  'Charles Jr.': [
    { year: 1952, gold: 2, silver: 1, bronze: 1 },
    { year: 1956, gold: 1, silver: 0, bronze: 0 },
    { year: 1960, gold: 1, silver: 0, bronze: 0 },
    { year: 1976, gold: 0, silver: 0, bronze: 0 },
    { year: 1992, gold: 1, silver: 0, bronze: 0 },
  ],
  'Nikolay Andrianov': [
    { year: 1972, gold: 1, silver: 1, bronze: 1 },
    { year: 1976, gold: 4, silver: 2, bronze: 1 },
    { year: 1980, gold: 2, silver: 2, bronze: 1 },
  ],
  'Borys Shakhlin': [
    { year: 1956, gold: 2, silver: 0, bronze: 0 },
    { year: 1960, gold: 4, silver: 2, bronze: 1 },
    { year: 1964, gold: 1, silver: 2, bronze: 1 },
  ],
};

const medalData = [
  { Afghanistan: 2 },
  { Albania: 2 },
  { Algeria: 20 },
  { Argentina: 80 },
  { Armenia: 22 },
  { Australasia: 12 },
  { Australia: 600 },
  { Austria: 105 },
  { Azerbaijan: 56 },
  { Bahamas: 16 },
  { Bahrain: 8 },
  { Barbados: 1 },
  { Belarus: 85 },
  { Belgium: 169 },
  { Bermuda: 2 },
  { Bohemia: 4 },
  { Botswana: 4 },
  { Brazil: 170 },
  { 'British West Indies': 2 },
  { Bulgaria: 231 },
  { 'Burkina Faso': 1 },
  { Burundi: 2 },
  { 'Cabo Verde': 1 },
  { Cameroon: 6 },
  { Canada: 354 },
  { Ceylon: 1 },
  { Chile: 15 },
  { China: 727 },
  { 'Chinese Taipei': 41 },
  { Colombia: 38 },
  { 'Costa Rica': 4 },
  { Croatia: 48 },
  { Cuba: 244 },
  { Cyprus: 2 },
  { 'Czech Republic': 72 },
  { Czechoslovakia: 146 },
  { Denmark: 216 },
  { Djibouti: 1 },
  { Dominica: 1 },
  { 'Dominican Republic': 15 },
  { 'East Germany': 409 },
  { Ecuador: 10 },
  { Egypt: 41 },
  { Eritrea: 1 },
  { Estonia: 36 },
  { Ethiopia: 62 },
  { 'FR Yugoslavia': 7 },
  { Fiji: 4 },
  { Finland: 306 },
  { Formosa: 1 },
  { France: 817 },
  { Gabon: 1 },
  { Georgia: 47 },
  { Germany: 704 },
  { Ghana: 5 },
  { 'Great Britain': 981 },
  { Greece: 129 },
  { Grenada: 5 },
  { Guatemala: 3 },
  { Guyana: 1 },
  { Haiti: 2 },
  { 'Hong Kong': 13 },
  { Hungary: 531 },
  { Iceland: 4 },
  { 'Independent Olympic Athletes': 2 },
  { 'Independent Olympic Participants': 3 },
  { India: 41 },
  { Indonesia: 40 },
  { Iran: 88 },
  { Iraq: 1 },
  { Ireland: 42 },
  { Israel: 20 },
  { Italy: 663 },
  { 'Ivory Coast': 5 },
  { Jamaica: 94 },
  { Japan: 544 },
  { Jordan: 4 },
  { Kazakhstan: 78 },
  { Kenya: 124 },
  { Kosovo: 5 },
  { Kuwait: 3 },
  { Kyrgyzstan: 13 },
  { Latvia: 21 },
  { Lebanon: 4 },
  { Lithuania: 30 },
  { Luxembourg: 3 },
  { Macedonia: 1 },
  { Malaysia: 15 },
  { Mauritius: 1 },
  { Mexico: 77 },
  { 'Mixed team': 25 },
  { Moldova: 10 },
  { Mongolia: 31 },
  { Montenegro: 1 },
  { Morocco: 26 },
  { Mozambique: 2 },
  { Namibia: 5 },
  { Netherlands: 357 },
  { 'Netherlands Antilles': 1 },
  { 'New Zealand': 157 },
  { Niger: 2 },
  { Nigeria: 27 },
  { 'North Korea': 60 },
  { 'North Macedonia': 1 },
  { Norway: 171 },
  { Pakistan: 11 },
  { Panama: 4 },
  { Paraguay: 1 },
  { Peru: 5 },
  { Philippines: 18 },
  { Poland: 313 },
  { Portugal: 32 },
  { 'Puerto Rico': 12 },
  { Qatar: 9 },
  { ROC: 71 },
  { 'Refugee Olympic Team': 1 },
  { Romania: 317 },
  { Russia: 423 },
  { 'Russian Empire': 8 },
  { 'Saint Lucia': 2 },
  { Samoa: 1 },
  { 'San Marino': 3 },
  { 'Saudi Arabia': 4 },
  { Senegal: 1 },
  { Serbia: 29 },
  { 'Serbia and Montenegro': 2 },
  { Singapore: 6 },
  { Slovakia: 33 },
  { Slovenia: 31 },
  { 'South Africa': 95 },
  { 'South Korea': 320 },
  { 'Soviet Union': 1010 },
  { Spain: 187 },
  { 'Sri Lanka': 1 },
  { Sudan: 1 },
  { Suriname: 2 },
  { Sweden: 516 },
  { Switzerland: 217 },
  { Syria: 4 },
  { Taiwan: 1 },
  { Tajikistan: 7 },
  { Tanzania: 2 },
  { Thailand: 41 },
  { Togo: 1 },
  { Tonga: 1 },
  { 'Trinidad and Tobago': 19 },
  { Tunisia: 18 },
  { Turkey: 111 },
  { Turkmenistan: 1 },
  { Uganda: 13 },
  { Ukraine: 151 },
  { 'Unified Team': 112 },
  { 'United Arab Emirates': 2 },
  { 'United States': 2764 },
  { 'United Team of Germany': 118 },
  { Uruguay: 10 },
  { Uzbekistan: 49 },
  { Venezuela: 19 },
  { Vietnam: 5 },
  { 'Virgin Islands': 1 },
  { 'West Germany': 204 },
  { Yugoslavia: 83 },
  { Zambia: 3 },
  { Zimbabwe: 8 },
];

export { athleteData, medalData };
